# Generated by Django 2.0.4 on 2018-05-19 14:14

import Posts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='active_days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='eyes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='haire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('age', models.CharField(max_length=10)),
                ('boob', models.CharField(max_length=5)),
                ('height', models.CharField(max_length=5)),
                ('weight', models.CharField(max_length=5)),
                ('note', models.TextField(max_length=500)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=Posts.models.file_location)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=Posts.models.file_location)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=Posts.models.file_location)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to=Posts.models.file_location)),
                ('image_5', models.ImageField(blank=True, null=True, upload_to=Posts.models.file_location)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_active', models.BooleanField(default=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('admin_active', models.BooleanField(default=False)),
                ('active_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.active_days')),
                ('eye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.eyes')),
                ('hair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.haire')),
            ],
        ),
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.types'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
