# Generated by Django 2.0.4 on 2018-06-06 12:07

import Posts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='eyes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='haire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('age', models.CharField(max_length=10)),
                ('boob', models.FloatField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=Posts.models.file_location)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=Posts.models.file_location)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=Posts.models.file_location)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to=Posts.models.file_location)),
                ('image_5', models.ImageField(blank=True, null=True, upload_to=Posts.models.file_location)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('appart_1', models.CharField(blank=True, default='-', max_length=10)),
                ('appart_2', models.CharField(blank=True, default='-', max_length=10)),
                ('appart_naigth', models.CharField(blank=True, default='-', max_length=10)),
                ('outside_1', models.CharField(blank=True, default='-', max_length=10)),
                ('outside_2', models.CharField(blank=True, default='-', max_length=10)),
                ('outside_nigth', models.CharField(blank=True, default='-', max_length=10)),
                ('sauna_1', models.CharField(blank=True, default='-', max_length=10)),
                ('sauna_2', models.CharField(blank=True, default='-', max_length=10)),
                ('sauna_night', models.CharField(blank=True, default='-', max_length=10)),
                ('active_counter', models.IntegerField(blank=True, default=0, null=True)),
                ('user_active', models.BooleanField(default=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('admin_active', models.BooleanField(default=False)),
                ('engleash', models.BooleanField(default=False)),
                ('eye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.eyes')),
                ('hair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.haire')),
            ],
        ),
        migrations.CreateModel(
            name='post_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.post_status'),
        ),
        migrations.AddField(
            model_name='post',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.types'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
