# Generated by Django 2.0.4 on 2018-06-03 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='appart_1',
            field=models.CharField(blank=True, default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='appart_2',
            field=models.CharField(blank=True, default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='appart_naigth',
            field=models.CharField(blank=True, default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='outside_1',
            field=models.CharField(blank=True, default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='outside_2',
            field=models.CharField(blank=True, default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='outside_nigth',
            field=models.CharField(blank=True, default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='sauna_1',
            field=models.CharField(blank=True, default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='sauna_2',
            field=models.CharField(blank=True, default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='sauna_night',
            field=models.CharField(blank=True, default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='active_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.post_status'),
        ),
    ]
