# Generated by Django 2.0.5 on 2018-05-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appart_1', models.CharField(blank=True, default='-', max_length=10)),
                ('appart_2', models.CharField(blank=True, default='-', max_length=10)),
                ('appart_naigth', models.CharField(blank=True, default='-', max_length=10)),
                ('outside_1', models.CharField(blank=True, default='-', max_length=10)),
                ('outside_2', models.CharField(blank=True, default='-', max_length=10)),
                ('outside_nigth', models.CharField(blank=True, default='-', max_length=10)),
                ('main_classic', models.BooleanField(default=False)),
                ('main_blowJob_w_condom', models.BooleanField(default=False)),
                ('main_cunni', models.BooleanField(default=False)),
                ('main_group_sex', models.BooleanField(default=False)),
                ('main_lesbi_lesbi', models.BooleanField(default=False)),
                ('mbr', models.BooleanField(default=False)),
                ('mbr_price', models.TextField(blank=True, max_length=10, null=True)),
                ('anal_sex', models.BooleanField(default=False)),
                ('anal_sex_price', models.TextField(blank=True, max_length=10, null=True)),
                ('dop_end_mouth', models.BooleanField(default=False)),
                ('dop_end_face', models.BooleanField(default=False)),
                ('dop_glub_minet', models.BooleanField(default=False)),
                ('dop_toys', models.BooleanField(default=False)),
                ('dop_role_game', models.BooleanField(default=False)),
                ('dop_couple_service', models.BooleanField(default=False)),
                ('dop_video', models.BooleanField(default=False)),
                ('dop_company', models.BooleanField(default=False)),
                ('massage_relax', models.BooleanField(default=False)),
                ('massage_classic', models.BooleanField(default=False)),
                ('massage_profi', models.BooleanField(default=False)),
                ('massage_tiski', models.BooleanField(default=False)),
                ('massage_prostat', models.BooleanField(default=False)),
                ('massage_erotic', models.BooleanField(default=False)),
                ('massage_sakura', models.BooleanField(default=False)),
                ('dance_profi', models.BooleanField(default=False)),
                ('dance_NoProfi', models.BooleanField(default=False)),
                ('dance_lesbi_show', models.BooleanField(default=False)),
                ('dance_lisbi', models.BooleanField(default=False)),
                ('sado_bandaj', models.BooleanField(default=False)),
                ('sado_gospoja', models.BooleanField(default=False)),
                ('sado_rabyn', models.BooleanField(default=False)),
                ('sado_dominant', models.BooleanField(default=False)),
                ('sado_porka', models.BooleanField(default=False)),
                ('sado_fetish', models.BooleanField(default=False)),
                ('sado_trampling', models.BooleanField(default=False)),
                ('extrim_anilingus', models.BooleanField(default=False)),
                ('extrim_dojd_out', models.BooleanField(default=False)),
                ('extrim_dojd_in', models.BooleanField(default=False)),
                ('extrim_strapon', models.BooleanField(default=False)),
                ('extrim_fisting_anal', models.BooleanField(default=False)),
                ('extrim_fisting_vagin', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.Post')),
            ],
        ),
    ]
