# Generated by Django 2.0.4 on 2018-06-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='appart_1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='appart_2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='appart_naigth',
        ),
        migrations.RemoveField(
            model_name='service',
            name='outside_1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='outside_2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='outside_nigth',
        ),
    ]
